# Generated by Django 4.2.9 on 2024-01-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='long_url',
            new_name='full_url',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='short_url',
            new_name='shortened_uri',
        ),
    ]
